# Generated by Django 5.0.6 on 2024-05-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Room',
        ),
    ]
